"""Add day plans and enhanced activities

Revision ID: 851877c17eb2
Revises: 
Create Date: 2025-11-01 16:45:41.832701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851877c17eb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create accommodations table first
    op.create_table('accommodations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('check_in', sa.DateTime(), nullable=False),
    sa.Column('check_out', sa.DateTime(), nullable=False),
    sa.Column('confirmation_number', sa.String(length=100), nullable=True),
    sa.Column('cost_per_night', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('booking_url', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create day_plans table
    op.create_table('day_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('accommodation_id', sa.Integer(), nullable=True),
    sa.Column('total_distance', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_rest_day', sa.Boolean(), nullable=True),
    sa.Column('weather_checked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Now modify activities table
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('all_day', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('booking_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('booking_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('photos', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('weather_dependent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('indoor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('accessibility', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('age_restriction', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dress_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('activity_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.create_foreign_key('fk_activities_day_plan_id', 'day_plans', ['day_plan_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_activities_created_by', 'users', ['created_by'], ['id'])
        batch_op.drop_column('is_booked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_booked', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint('fk_activities_created_by', type_='foreignkey')
        batch_op.drop_constraint('fk_activities_day_plan_id', type_='foreignkey')
        batch_op.alter_column('activity_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('completed_at')
        batch_op.drop_column('created_by')
        batch_op.drop_column('tags')
        batch_op.drop_column('dress_code')
        batch_op.drop_column('age_restriction')
        batch_op.drop_column('accessibility')
        batch_op.drop_column('indoor')
        batch_op.drop_column('weather_dependent')
        batch_op.drop_column('photos')
        batch_op.drop_column('review')
        batch_op.drop_column('rating')
        batch_op.drop_column('website')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_phone')
        batch_op.drop_column('paid')
        batch_op.drop_column('currency')
        batch_op.drop_column('booking_status')
        batch_op.drop_column('booking_required')
        batch_op.drop_column('status')
        batch_op.drop_column('all_day')
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('address')
        batch_op.drop_column('day_plan_id')
    
    op.drop_table('day_plans')
    op.drop_table('accommodations')

    # ### end Alembic commands ###
